Algoritmo "Exe2"

Var
  numero1 : real
  numero2 : real


Inicio
   escreva("Digite o primeiro numero: ")
   leia(numero1)
      
   escreva("Digite o segundo numero: ")
   leia(numero2)
      
      se(numero1 > numero2)entao
                 escreva("O primeiro numero é maior que o segundo")
      senao(numero1 < numero2)entao
                 escreva("O segundo numero é maior que o primeiro")
      fimse



Fimalgoritmo