Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2020
Var
 n1, n2, soma : inteiro


Inicio
 escreva("digite o primeiro numero: ")
 leia(n1)
 
 escreva("digite o segundo numero: ")
 leia(n2)
 
 soma <- n1 + n2
 
 escreva("A soma dos numeros é: ", soma)


Fimalgoritmo